---
title: "GitHub e Git"
author: "Claudiane Pereira da silva"
date: "2023-12-06"
output:
  word_document: default
  html_document: default
---


## O que é Git ?
Git é um sistema de controle de versão distribuído amplamente utilizado para o rastreamento de alterações em projetos de software. Ele permite que várias pessoas trabalhem em um projeto simultaneamente, controlando as diferentes versões do código-fonte. Com o Git, você pode acompanhar as alterações, criar ramificações para desenvolver novos recursos ou corrigir bugs, e mesclar essas alterações de volta à versão principal do projeto. É uma ferramenta poderosa para colaboração e gerenciamento de código

## O que é GitHub
O GitHub é uma plataforma de hospedagem de código-fonte que utiliza o Git para controle de versão. Ele facilita a colaboração entre desenvolvedores, permitindo o armazenamento de projetos em repositórios, o rastreamento de alterações, a abertura de problemas e a integração contínua. É fundamental para o desenvolvimento de software colaborativo e eficiente.

## Como configurar o Git no pc?
Instale o Git no seu computador.
Configure seu nome e e-mail usando comandos do Git.
Crie uma conta no GitHub, se ainda não tiver.
Opcional: Configure autenticação SSH para maior segurança.
No GitHub, crie um novo repositório.
No terminal, use git clone para baixar o repositório localmente.

git config --global user.name "Seu Nome"
git config --global user.email "seu@email.com"
git config --global --list

# Conceitos básicos:
## Repositórios:
Os projetos no GitHub são armazenados em repositórios, que são estruturas que contêm todos os arquivos, histórico de alterações e outras informações relacionadas a um projeto.

## Pull request
É uma solicitação feita por um colaborador para mesclar suas alterações de um branch para o branch principal do repositório. Facilita a revisão e discussão antes da integração.

## Clone
Fazer um clone de um repositório significa baixar uma cópia do projeto para o seu computador. Isso permite que você trabalhe localmente no código.
git clone URL_DO_REPOSITORIO
git clone https://github.com/usuario/nome-do-repositorio.git
git clone https://github.com/usuario/nome-do-repositorio.git nome-do-diretorio


## Branch
Um branch é uma ramificação do código-fonte. Você pode criar branches para desenvolver novos recursos ou corrigir bugs sem afetar a versão principal do projeto.
git branch nome_da_nova_branch
git checkout nome_da_branch_existente
git checkout -b nome_da_nova_branch
git branch
git branch -r
git branch -d nome_da_branch
git branch -D nome_da_branch
git branch -m novo_nome_da_branch



## Commit
Um commit é uma alteração feita no código. Após realizar alterações, você faz um commit para registrar essas mudanças no histórico do Git.
git add nome_do_arquivo
git add .
git commit -m "Mensagem do Commit"
git commit -am "Mensagem do Commit"


## Pull
Atualiza o seu repositório local com as últimas alterações do repositório remoto.
git pull origin nome_da_branch
git pull origin main


## Push
 "push" significa enviar as alterações locais para o repositório remoto, garantindo que o código no servidor seja atualizado com as suas últimas modificações. 
 
## Merge
 O "merge" é o processo de combinar alterações de diferentes branches no Git. Ele é frequentemente associado aos "Pull Requests" no GitHub. Após trabalhar em uma branch (por exemplo, para desenvolver uma nova funcionalidade), você abre um Pull Request para sugerir a mesclagem das alterações de volta para a branch principal.
 git checkout branch_destino
git checkout branch_destino
# Alternar para a branch de destino
git checkout main

# Realizar o merge da branch de origem
git merge feature-branch

git merge --abort


 
## Status 
O comando "git status" no Git e GitHub fornece informações sobre o estado do seu repositório. Um resumo típico inclui:

Arquivos modificados: Listagem dos arquivos com alterações.
Arquivos não rastreados: Novos arquivos não adicionados ao controle de versão.
Ramificação atual: Nome da branch em que você está.
Commits a serem confirmados: Alterações prontas para serem confirmadas.

git status


## Checkout
O comando "git status" no Git e GitHub fornece informações sobre o estado do seu repositório. Um resumo típico inclui:

Arquivos modificados: Listagem dos arquivos com alterações.
Arquivos não rastreados: Novos arquivos não adicionados ao controle de versão.

git checkout nome_da_branch
git checkout -b nome_da_nova_branch
git checkout commit_hash
git checkout -- nome_do_arquivo
git checkout -- .
git checkout -

Ramificação atual: Nome da branch em que você está.
Commits a serem confirmados: Alterações prontas para serem confirmadas.
